<div id="manage-scanforms">
    <table id="scanform-table" class="table table-bordered table-striped table-hover">
        <thead>
            <tr>
                <td colspan="6">
                    <div id="prepare-form">
                        <form class="form-inline" role="form">
                            <div class="form-group">
                                <select class="form-control" name="customer">
                                    <option value="">Please select a customer</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <select class="form-control" disabled="disabled" name="batch">
                                    <option value="">Please select a batch</option>
                                </select>
                            </div>
                        </form>
                    </div>
                </td>
            </tr>
            <tr>
                <th>Name</th>
                <th>Made on</th>
                <th colspan="3"><a href="#" class="edit-scanform hide pull-right">New</a></th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>
</div>
<div id="manage-recipients" class="hide">
    <form id="manage-recipients-form">
        <input type="hidden" name="scanFormId" />
        <div class="row">
            <div class="col-md-5">
                <select name="add[]" multiple class="form-control">
                </select>
            </div>
            <div class="col-md-2">
                <div class="scan-form-controls">
                    <a href="#" class="btn btn-default form-control move-recipients" data-move-from="add" data-move-to="remove">Add <span class="glyphicon glyphicon-arrow-right"></span></a>
                    <a href="#" class="btn btn-default form-control move-recipients" data-move-from="remove" data-move-to="add"><span class="glyphicon glyphicon-arrow-left"></span> Remove</a>
                </div>
            </div>
            <div class="col-md-5">
                <select name="remove[]" multiple class="form-control">
                </select>
            </div>
        </div>
        <div class="row">
            <div class="col-md-5">
                <a href="#">Select All</a>
            </div>
            <div class="col-md-2">
                <a href="#" class="btn btn-primary form-control" id="cancel-manage-recipients">Close</a> &nbsp;
            </div>
            <div class="col-md-5">
                <a href="#" class="pull-right">Select All</a>
            </div>
        </div>
    </form>
</div>
<div class="modal fade" id="edit-scanform-dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal" id="edit-scanform-form">
                    <div class="form-group">
                        <label class="col-lg-3 control-label" for="email">Email</label>
                        <div class="controls col-lg-6">
                            <input type="hidden" name="batchId" />
                            <input type="hidden" name="scanFormId" />
                            <input type="text" class="form-control" name="name" placeholder="Name" />
                            <p class="help-block"></p>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="save-scanform-form">Save</button>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="generate-dialog">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to generate? Once a scan form is generated, you can not refund or cancel any stamps to the recipients of the scan form.</p>
                <p>You will also not be able to move any of the recipients to another scan form.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary" data-scan-form-id="" id="generate-submit">Generate</button>
            </div>
        </div>
    </div>
</div>