<table id="customer-table" class="table table-bordered table-striped table-hover">
    <thead>
        <tr>
            <th>Name</th>
            <th>Active</th>
            <th><a href="#" id="add-customer-button" class="edit-customer-button">Add Customer</a></th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>
<div class="modal fade" id="edit-customer-dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal" id="edit-customer-form">
                    <div class="form-group">
                        <label class="col-lg-3 control-label" for="name">Name</label>
                        <div class="controls col-lg-6">
                            <input type="hidden" name="customerId" />
                            <input type="text" class="form-control" name="name" placeholder="Name" />
                            <p class="help-block"></p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-3 control-label" for="active">Active</label>
                        <div class="controls col-lg-6">
                            <select name="active" class="form-control" >
                                <option value="">Select a value</option>
                                <option value="true">Yes</option>
                                <option value="false">No</option>
                            </select>
                            <p class="help-block"></p>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="save-customer-form">Save</button>
            </div>
        </div>
    </div>
</div>