<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="shortcut icon" type="image/png" href="/img/dhfavicon.png">

        <title>Dark Horse</title>

        <!-- Bootstrap core CSS -->
        <link href="/css/bootstrap.min.css" rel="stylesheet">
        <link href="/css/site.css" rel="stylesheet">
        <?= $this->headLink() ?>

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <?php echo $this->partial('partials/menu.phtml', 'default'); ?>
        <div class="container">
            <?= $this->layout()->content; ?>
        </div>
        <script src="/js/library/jquery-1.10.2.min.js" type="text/javascript"></script>
        <script src="/js/library/jquery.validate.min.js" type="text/javascript"></script>
        <script src="/js/library/bootstrap.min.js" type="text/javascript"></script>
        <script src="/js/darkhorse.js" type="text/javascript"></script>
        <?= $this->headScript() ?>
</body>
</html>
