<table id="prepare-table" class="table table-bordered table-striped table-hover">
    <thead>
        <tr>
            <td colspan="4">
                <div id="prepare-form">
                    <form class="form-inline" role="form">
                        <div class="form-group">
                            <select class="form-control" name="customer">
                                <option value="">Please select a customer</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <select class="form-control" disabled="disabled" name="batch">
                                <option value="">Please select a batch</option>
                            </select>
                        </div>
                    </form>
                </div>
            </td>
        </tr>
        <tr>
            <th>Sex</th>
            <th>Size</th>
            <th>Type</th>
            <th>Weight</th>
        </tr>
    </thead>
    <tbody></tbody>
</table>
