<table id="print-table" class="table table-bordered table-striped table-hover">
    <thead>
        <tr>
            <td colspan="7">
                <div id="prepare-form">
                    <form class="form-inline" role="form">
                        <div class="form-group">
                            <select class="form-control" name="customer">
                                <option value="">Please select a customer</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <select class="form-control" disabled="disabled" name="batch">
                                <option value="">Please select a batch</option>
                            </select>
                        </div>
                    </form>
                </div>
            </td>
        </tr>
        <tr class="table-tools" style="display:none;">
            <td colspan="7">
                <div class="row">
                    <div class="col-md-3">
                        <form class="form-inline" role="form">
                            <div class="form-group">
                                <select class="form-control" name="page-count">
                                    <option value="10">10</option>
                                    <option value="25">25</option>
                                    <option value="50">50</option>
                                    <option value="100">100</option>
                                    <option value="500">500</option>
                                </select>
                                records per page
                            </div>
                        </form>
                    </div>
                    <div class="col-md-6">
                        <ul class="pagination">
                        </ul>
                    </div>
                    <div class="col-md-3">
                        <div class="btn-group pull-right">
                            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                Print
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu print-selection">
                                <li><a href="#" data-printtype="unshipped">Print Unshipped</a></li>
                                <li><a href="#" data-printtype="unverified">Print Unverified</a></li>
                                <li><a href="#" data-printtype="all">Print All</a></li>
                                <li class="divider"></li>
                                <li><a href="#" data-printtype="cancel">Cancel All</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </td>
        </tr>
        <tr>
            <th>Email</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Verified</th>
            <th>Ship Date</th>
            <th>Tracking #</th>
            <th></th>
        </tr>
    </thead>
    <tbody></tbody>
</table>
<div class="modal fade" id="print-dialog">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body">
                <p>Do you wish to print?</p>
                <div class="progress progress-striped active">
                    <div class="progress-bar"  role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="0" style="width: 0%">
                        <span class="sr-only">Working</span>
                    </div>
                </div>
                <div class="progress-text"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" data-printtype="" id="print-submit">Print</button>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="cancel-dialog">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Cancel Postage</h4>
            </div>
            <div class="modal-body">
                <p>You may only cancel packages which have not had a scan form generated or shipped. Cancel all available stamps?</p>
                <div class="progress progress-striped active">
                    <div class="progress-bar"  role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="0" style="width: 0%">
                        <span class="sr-only">Working</span>
                    </div>
                </div>
                <div class="progress-text"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="cancel-submit">Cancel</button>
            </div>
        </div>
    </div>
</div>
<div class="applet">

</div>
    <applet id="qz" name="QZ Print Plugin" code="qz.PrintApplet.class" archive="/js/library/qz-print.jar" width="100" height="100">
        <param name="printer" value="zebra">
        <param name="jnlp_href" value="/js/library/qz-print_jnlp.jnlp">
        <param name="cache_option" value="plugin">
        <param name="disable_logging" value="false">
        <param name="initial_focus" value="false">
    </applet>