<?php $url = sprintf('/%s/%s/%s',
        $module = Zend_Controller_Front::getInstance()->getRequest()->getModuleName(),
        $controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName(),
        $action = Zend_Controller_Front::getInstance()->getRequest()->getActionName()
      ); ?>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Dark Horse</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
            <?php if(Zend_Registry::get(SESSION)->userTypeId == USER_TYPE_ADMIN) { ?>
                <li <?= $url=='/default/users/index'?'class="active"':''; ?>><a href="/users">Users</a></li>
                <li <?= $url=='/default/customer/index'?'class="active"':''; ?>><a href="/customer">Customers</a></li>
                <li <?= $url=='/default/batch/index'?'class="active"':''; ?>><a href="/batch">Batches</a></li>
                <li <?= $url=='/default/recipient/index'?'class="active"':''; ?>><a href="/recipient">Recipients</a></li>
                <li class="dropdown <?= $controller == 'postage' ? 'active' : '' ?>">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Postage <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="/postage/prepare">Prepare</a></li>
                        <li><a href="/postage/view">Print</a></li>
                    </ul>
                </li>
             <?php } elseif(Zend_Registry::get(SESSION)->userTypeId == USER_TYPE_EMPLOYEE) { ?>

            <?php } ?>
                <li><a href="/auth/logout">Logout</a></li>
            </ul>

        </div><!--/.nav-collapse -->
    </div>
</div>

