<?php $url = sprintf('/%s/%s/%s',
        $module = Zend_Controller_Front::getInstance()->getRequest()->getModuleName(),
        $controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName(),
        $action = Zend_Controller_Front::getInstance()->getRequest()->getActionName()
      ); ?>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Dark Horse</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
            <?php if(Zend_Registry::get(SESSION)->userTypeId == USER_TYPE_ADMIN) { ?>
                <li <?= $url=='/default/users/index'?'class="active"':''; ?>><a href="/users">Users</a></li>
                <li <?= $url=='/default/customer/index'?'class="active"':''; ?>><a href="/customer">Customers</a></li>
                <li <?= $url=='/default/batch/index'?'class="active"':''; ?>><a href="/batch">Batches</a></li>
                <li <?= $url=='/default/recipient/index'?'class="active"':''; ?>><a href="/recipient">Recipients</a></li>
                <li class="dropdown <?= $controller == 'postage' ? 'active' : '' ?>">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Postage <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="/postage/prepare">Prepare</a></li>
                        <li><a href="/postage/view">Print</a></li>
                        <li><a href="/scanform">Scan Form</a></li>
                    </ul>
                </li>
             <?php } elseif(Zend_Registry::get(SESSION)->userTypeId == USER_TYPE_EMPLOYEE) { ?>

            <?php } ?>
                <li><a href="/auth/logout">Logout</a></li>

            </ul>
            <ul class="nav navbar-nav pull-right">
                <li><a href="#" id="account-balance"  data-toggle="modal" data-target="#add-funds">
                    Balance <span></span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>
<div class="modal fade" id="add-funds" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <form class="form-horizontal" role="form">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">Add funds</h4>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="amount" class="col-sm-2 control-label">Amount</label>
                        <div class="col-sm-6">
                            <select class="form-control" name="amount">
                                <option value="10">$10</option>
                                <option value="25">$25</option>
                                <option value="50">$50</option>
                                <option value="100">$100</option>
                                <option value="250">$250</option>
                                <option value="500">$500</option>
                                <option value="1000">$1,000</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="button" id="make-purchase" class="btn btn-primary">Purchase</button>
                </div>
            </div>
        </form>
    </div>
</div>
